Add migrations and models, income, user, payments
andreyshilov0/finance-accounting-calendar-backend pull request #1
Opened 2023-08-09 16:32 UTC by andreyshilov0

2023-08-10 07:56 UTC, reshetov requested changes

2023-08-10 07:56 UTC, reshetov commented on app/models/income_category.rb
> +  has_many :incomes
Когда пишешь has_many, всегда нужно еще dependent (https://apidock.com/rails/ActiveRecord/Associations/ClassMethods/has_many) указывать.
Что будет если удалить категорию? Как себя при этом "поступления" поведут?

2023-08-10 07:56 UTC, reshetov commented on app/models/payment_category.rb
> +  has_many :payments
см. выше

2023-08-10 07:56 UTC, reshetov commented on app/models/user.rb
> +  has_many :user_incomes
см. выше (всегда задавай вопрос себе, а что будет если я удалю "пользователя"/"категорию"/т.п.?)

2023-08-10 07:56 UTC, reshetov commented on app/models/user_income.rb
> +class UserIncome < ApplicationRecord
У тебя эта модель будет ипользоваться только для связи (в ней не будет других полей кроме как user_id, income_id). Для таких случаев в Rails используют немного другую ассоциацию has_and_belongs_to_many (http://rusrails.ru/active-record-associations#svyaz-has_and_belongs_to_many) она позволяет делать тоже самое что и ты сейчас, но без создания отдельного класса для связующей таблицы. Поменяй на нее, только почитай повнимательнее, там нужно быть внимательным с именем таблицы

2023-08-10 07:56 UTC, reshetov commented on app/models/user_payment.rb
> +class UserPayment < ApplicationRecord
см. выше

2023-08-10 07:56 UTC, reshetov commented on db/migrate/20230808132822_create_income_categories.rb
> +      t.string :name, null: false
Ты будешь по этому искать? Если ответ да - нужно индекс добавлять на поле

2023-08-10 07:56 UTC, reshetov commented on db/migrate/20230808132846_create_payment_categories.rb
> +      t.string :name, null: false
Тот же вопрос

2023-08-10 07:56 UTC, reshetov commented on db/migrate/20230808134211_create_incomes.rb
> +      t.float :amount, precision: 10, scale: 2, null: true
А чего это у тебя сумма null может быть?

2023-08-10 07:56 UTC, reshetov commented on db/migrate/20230808135442_create_payments.rb
> +      t.float :amount, precision: 10, scale: 2, null: true
и тут

2023-08-10 07:56 UTC, reshetov commented on db/migrate/20230809123138_create_user_incomes.rb
> +      t.references :user, null: false, foreign_key: true
Вот тут давай еще раз сядь и все переодумай, у тебя какая-то дичь тут
1. У тебя есть таблица incomes, в которой есть user_id, income_category_id, amount -> т.е. она по идее может хранить данные по платежу
2. В этой таблице у тебя есть user_id, income_category_id, amount  -> т.е. она тоже может хранить данные по платежу

Вопрос - зачем тебе два таблицы (модели) которые делают одно и тоже? Мне кажется ты что-то одно задумал, но потом передумал и сделал по другому

2023-08-10 07:56 UTC, reshetov commented on db/migrate/20230809123208_create_user_payments.rb
> +      t.references :user, null: false, foreign_key: true
Тоже самое что и выше

2023-08-18 07:26 UTC, reshetov requested changes

2023-08-18 07:26 UTC, reshetov commented on app/models/income.rb
> +    update(deleted: true) if income_category_id.present?
Тут не факт что сработает, обновить то обновит, но это не оставит удаление и запись через мгновение будет удалена.
Если не ошибаюсь тут нужно false возвращать чтобы остановить процесс удаления.
Либо можно вообще не вызывать удаление для объекта, а в методе destroy в контроллере просто обновлять поле deleted, так у тебя останется возможность удалить объект и не нужно будет колбеки писать

2023-08-18 07:26 UTC, reshetov commented on app/models/income_category.rb
> +    incomes.update_all(deleted: true, income_category_id: nil)
У тебя уже есть  dependent: :nullify, категорию он занулит

2023-08-18 07:26 UTC, reshetov commented on app/models/payment.rb
> +    update(deleted: true) if payment_category_id.present?
см. выше про поступление

2023-08-18 07:26 UTC, reshetov commented on app/models/payment_category.rb
> +  has_and_belongs_to_many :users
Зачем прямая связь пользователей и категорий? Они через платежи должны связываться

2023-08-18 07:26 UTC, reshetov commented on app/models/payment_category.rb
> +    payments.update_all(deleted: true, payment_category_id: nil)
см. выше про категории

2023-08-18 07:26 UTC, reshetov commented on app/models/user.rb
> +  has_and_belongs_to_many :income_categories
Зачем? И как это будет работать? Когда ты создашь платеж никто не запишет в таблицу payments_users данные, это нужно будет отдельным действием делать. Но я вообще не вижу в этом смысла, категории всегда можно достать через платежи/поступления

2023-08-18 07:26 UTC, reshetov commented on app/models/user.rb
> +  has_and_belongs_to_many :payment_categories
+1

2023-08-18 07:26 UTC, reshetov commented on db/migrate/20230808134211_create_incomes.rb
> +      t.references :income_category, foreign_key: true
Ты не сможешь занулить категорию если у тебя на нее внешний ключ указывает - база не даст.
Ты когда миграции делаешь - открой консоль и попробуй посоздавать/поудалять объекты и ты легко увидишь что не так у тебя

2023-08-18 07:26 UTC, reshetov commented on db/migrate/20230808135442_create_payments.rb
> +      t.references :payment_category, foreign_key: true
см. выше

2023-08-18 07:26 UTC, reshetov commented on db/migrate/20230816120712_create_user_income_join_table.rb
> +    create_join_table :users, :income_categories do |t|
Мое мнение - не нужны эти таблицы (я тебе об том на созвоне говорил кстати) или объясни мне обратное

2023-08-18 07:26 UTC, reshetov commented on db/migrate/20230816120739_create_user_payment_join_table.rb
> +    create_join_table :users, :payment_categories do |t|
+1

2023-08-21 16:02 UTC, andreyshilov0 commented on app/models/user.rb
> +  has_and_belongs_to_many :income_categories
Это наверное единственная модель которую я не могу понять до конца, если создавать ассоциацию 
User => Income - через has_many, то мы сможем сделать dependent:destroy для пользователя что логично удалять все платежи у пользователя.
если же сделать другую связь 
User => Income - через has_and_belongs_to_many , мы как я понимаю dependent уже юзать тут не можем, тогда как нам это делать? 
Потому что ты выше писал о том что связь между User и Income должна быть осуществлена через has_and_belongs_to_many, соответственно пользователь имеет доступ к своим платежам , а через платежи он уже получит доступ к категориям.  Тут может я конечно запутался но вроде бы ты так сказал. Хотя у меня есть предположение по поводу опции :autosave , но не до конца уверен. Я попробовал сделать через has_and_belongs_to_many, вроде бы всё работает, но лучше уточни пожалуйста.

2023-08-21 16:02 UTC, andreyshilov0 commented on db/migrate/20230816120712_create_user_income_join_table.rb
> +    create_join_table :users, :income_categories do |t|
join_table я нашел тоже в доке (http://rusrails.ru/active-record-migrations#sozdanie-soedinitelnoy-tablitsy), когда разбирался со связями, а так же прочитал что якобы через него идёт более быстрый поиск, но тут могу ошибаться потому что в разных источниках разное пишут. Но я переписал на самый первый способ который в миграциях описывается.

2023-08-22 07:33 UTC, reshetov commented on db/migrate/20230816120712_create_user_income_join_table.rb
> +    create_join_table :users, :income_categories do |t|
У тебя эта миграция создаст в базе таблицу users_income_categories в которой подразумевается что будут лежать связи "user -- income category", но кто их туда положит? Сами они автоматом не будут созданы при добавлении нового income.
Это можно либо отдельный кодом сделать, но опять таки возникает вопрос - зачем делать отдельные связи если эти же данные можно всегда достать через связи пользователя с income, сейчас это по сути дублирование данных

2023-08-22 12:05 UTC, reshetov commented on app/models/user.rb
> +  has_and_belongs_to_many :income_categories
"Потому что ты выше писал о том что связь между User и Income должна быть осуществлена через has_and_belongs_to_many, соответственно пользователь имеет доступ к своим платежам"
А потом мы еще час с тобой обсуждали что и как связно должно быть и я там тебе говорил что эти связи лишние, еще и рисовал это все на экране - это ты уже не помнишь?

2023-08-25 05:57 UTC, reshetov requested changes

2023-08-25 05:57 UTC, reshetov commented on db/migrate/20230808134211_create_incomes.rb
> +      t.references :income_category, foreign_key: false
Зачем писать foreign_key: false - это значение по-умолчанию, можно просто его не указывать

2023-08-25 05:57 UTC, reshetov commented on db/migrate/20230808135442_create_payments.rb
> +      t.references :payment_category, foreign_key: false
см. выше

2023-08-25 05:57 UTC, reshetov commented on app/controllers/actions/incomes_categories_controller.rb
> +  def mark_deleted
Вот это я вообще не понял что такое, мы пока вроде схему еще крутим.

2023-08-25 05:57 UTC, reshetov commented on app/controllers/actions/incomes_categories_controller.rb
> +    @income_category = IncomeCategory.find(params[:id])
А если не найдет? Обработает корректно или 500 вывалит?

2023-08-25 05:57 UTC, reshetov commented on app/controllers/actions/incomes_categories_controller.rb
> +    # Решил оставить пока эти два метода без коллбэков для смены флажка, далее для graphql уже допишу всё что понадобиться
Не нужно коментов в коде, хочешь что-то сказать - напиши в сообщении тут или в чате

2023-08-25 12:54 UTC, reshetov approved these changes

2023-08-25 12:54 UTC, merged